Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,7 +40,8 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: CustomVehicles-Windows
-          path: build/CustomVehicles.dll
+          path: |
+            **/CustomVehicles.dll
 
   build-linux:
     name: Build Linux SO (x86)
@@ -54,4 +55,24 @@ jobs:
         run: sudo apt-get update && sudo apt-get install -y g++-multilib
 
       - name: Create build directory
-        run: mkdir -p bui
+        run: mkdir -p build
+
+      - name: Compile plugin (Linux)
+        shell: bash
+        run: |
+          FILE=$(find . -name "CustomVehicles.cpp" | head -n 1)
+          echo "🔍 Found source file: $FILE"
+          if [ -z "$FILE" ]; then
+            echo "❌ CustomVehicles.cpp not found!"
+            exit 1
+          fi
+          g++ -m32 -std=c++17 -fPIC -O2 -static-libgcc -static-libstdc++ \
+              -shared "$FILE" -o build/CustomVehicles.so
+          echo "✅ Build finished: build/CustomVehicles.so"
+
+      - name: Upload SO
+        uses: actions/upload-artifact@v4
+        with:
+          name: CustomVehicles-Linux
+          path: |
+            **/CustomVehicles.so
